server.port=8091

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5435/academic_repo
spring.datasource.username=academicuser
spring.datasource.password=academicpass

# JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

# Liquibase Migration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Terminal
spring.output.ansi.enabled=always
